### ISSUE TITLE
遇到一个bug,

### ISSUE THREAD

**Issue by dzjwan521** [helicopters/wc-view#2]
![image](https://user-images.githubusercontent.com/26075682/34077361-14b56b48-e33d-11e7-9c75-e4d9d92ff072.png)
`
 let articleContent=this.$refs.articleContent
                                    let imgs = articleContent.getElementsByTagName('img');
                                    console.log(imgs);
                                    for(let i=0;i<imgs.length;i++){
                                        (function(i){
                                             imgs[i].addEventListener('click',()=>{
                                                 _this.$preview(event, _this.listData.vidFileList, i,'path');
                                             })
                                        })(i)
                                    }
`

我吧图中透明度调为1就好了

**Comment by helicopters** [comment]
@dzjwan521 这个bug怎么遇见的， 我看下能不能在我这边重现一下.

**Comment by dzjwan521** [comment]
@helicopters  我调用你插件的方式和你的文档中的不一样   因为项目原因  我用获取dom的方式获取到所有img元素  然后用去绑定事件的方式  去调用这个api,就出现了 我已经把你源码里面设置透明度的代码强制设置为1   解决了目前的问题
 _this.$preview(event, _this.listData.vidFileList, i,'path');
