### ISSUE TITLE
pc端兼容问题

### ISSUE THREAD

**Issue by dzjwan521** [helicopters/wc-view#3]
PC端无法用鼠标切换图片

**Comment by helicopters** [comment]
@dzjwan521 我没有做pc端处理, 这会我看下吧哈哈，待会给你说结果.

**Comment by dzjwan521** [comment]
@helicopters   谢谢了   我项目太紧急  没时间去看你代码了    今天要是能解决就帮了我大忙   感谢!~~~

**Comment by helicopters** [comment]
@dzjwan521  hi, pc 端兼容已经处理好了。 你可以重新安装一下 wc-view。 
问题造成原因记录:  view 使用了我的另外一个组件 wc-swiper,  wc-swiper 在pc端实际上是兼容的。 但是没有对图片的默认拖拽效果做去除。 所以改了一下 wc-swiper。 然后 pc 端滑动和 view 上面绑定的点击事件(用来关闭预览) 冲突. 所以做了一下处理： 移动端依旧是点击预览关闭，pc端需要双击才能关闭。 同时在预览右上角加了一个 关闭按钮 (用户可控制显示与否).

**Comment by dzjwan521** [comment]
@helicopters   thx!
